// plugins/single-player-limit/assets/BindPlayer.svelte
<script lang="ts">
  import { onMount } from 'svelte'

  const { base_url, fetch, notify, t } = globalThis.blessing

  type Player = {
    pid: number
    name: string
    uid: number
    tid_skin: number
    tid_cape: number
    last_modified: string
  }

  let isLoading = false
  let isSubmitting = false

  let players: string[] = []
  let selected = ''

  onMount(async () => {
    isLoading = true
    try {
      const data = await fetch.get<Player[]>('/user/player/list')
      players = data.map(({ name }) => name)
      selected = players[0]
    } finally {
      isLoading = false
    }
  })

  async function handleSubmit() {
    isSubmitting = true
    try {
      const {
        code,
        message,
      }: {
        code: number
        message: string
      } = await fetch.post('/user/player/bind', {
        player: selected,
      })
      if (code === 0) {
        await notify.showModal({
          mode: 'alert',
          text: message,
        })
        location.assign(`${base_url}/user`)
      } else {
        notify.showModal({ mode: 'alert', text: message })
      }
    } finally {
      isSubmitting = false
    }
  }
</script>

{#if isLoading}
  <p>Loading...</p>
{:else}
  <form method="post" on:submit|preventDefault={handleSubmit}>
    {#if players.length > 0}
      <p>{t('single-player-limit.bindExistedPlayer')}</p>
      <div class="mb-3">
        {#each players as player (player)}
          <label class="d-block mb-1">
            <input
              type="radio"
              class="mr-2"
              checked={selected === player}
              on:change={() => (selected = player)}
            />
            {player}
          </label>
        {/each}
      </div>
    {:else}
      <p>{t('single-player-limit.bindNewPlayer')}</p>
      <input
        type="text"
        class="form-control mb-3"
        placeholder={t('general.player.player-name')}
        on:change={(e) => (selected = e.currentTarget.value)}
      />
    {/if}
    <button
      class="btn btn-primary float-right"
      type="submit"
      disabled={isSubmitting}
    >
      {#if isSubmitting}
        <i class="fas fa-spinner fa-spin mr-1" />
        {t('general.wait')}
      {:else}
        {t('general.submit')}
      {/if}
    </button>
  </form>
{/if}

// single-player-limit/assets/BindPlayer.tsx
type Player = {
  pid: number
  name: string
  uid: number
  tid_skin: number
  tid_cape: number
  last_modified: string
}

const BindPlayer: React.FC = () => {
  const [players, setPlayers] = React.useState<string[]>([])
  const [selected, setSelected] = React.useState('')
  const [isLoading, setIsLoading] = React.useState(false)
  const [isPending, setIsPending] = React.useState(false)

  React.useEffect(() => {
    const getPlayers = async () => {
      setIsLoading(true)
      const data = await blessing.fetch.get<Player[]>('/user/player/list')
      const players = data.map((player) => player.name)
      setPlayers(players)
      setSelected(players[0])
      setIsLoading(false)
    }
    getPlayers()
  }, [])

  const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    setIsPending(true)

    const {
      code,
      message,
    }: {
      code: number
      message: string
    } = await blessing.fetch.post('/user/player/bind', { player: selected })
    if (code === 0) {
      await blessing.notify.showModal({ mode: 'alert', text: message })
      window.location.href = `${blessing.base_url}/user`
    } else {
      blessing.notify.showModal({ mode: 'alert', text: message })
    }

    setIsPending(false)
  }

  return isLoading ? (
    <p>Loading...</p>
  ) : (
    <form method="post" onSubmit={handleSubmit}>
      {players.length > 0 ? (
        <>
          <p>{trans('single-player-limit.bindExistedPlayer')}</p>
          <div className="mb-3">
            {players.map((player) => (
              <label key={player} className="d-block mb-1">
                <input
                  type="radio"
                  className="mr-2"
                  checked={selected === player}
                  onChange={() => setSelected(player)}
                />
                {player}
              </label>
            ))}
          </div>
        </>
      ) : (
        <>
          <p>{trans('single-player-limit.bindNewPlayer')}</p>
          <input
            type="text"
            className="form-control mb-3"
            placeholder={trans('general.player.player-name')}
            onChange={(e) => setSelected(e.target.value)}
          />
        </>
      )}
      <button
        className="btn btn-primary float-right"
        type="submit"
        disabled={isPending}
      >
        {isPending ? (
          <>
            <i className="fas fa-spinner fa-spin mr-1"></i>
            {trans('general.wait')}
          </>
        ) : (
          trans('general.submit')
        )}
      </button>
    </form>
  )
}

ReactDOM.render(<BindPlayer />, document.querySelector('#form'))
