// plugins/texture-description/assets/Description.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { fetch, t, notify } from 'blessing-skin'

  let description = ''
  let raw = ''
  $: isEmptyDescription = description.trim() === ''

  let canEdit = false
  let isEditing = false
  let isSubmitting = false
  let maxLength = Infinity
  $: isLengthExceeded = (raw?.length ?? 0) > maxLength

  function parseTid(): string {
    const { pathname } = location
    const matches = /(\d+)$/.exec(pathname)

    return matches?.[1] ?? '0'
  }

  onMount(async () => {
    const tid = parseTid()
    description = await fetch.get(`/texture/${tid}/description`)
  })

  onMount(() => {
    const el = document.querySelector<HTMLDivElement>('#texture-description')
    const dataset = el?.dataset
    canEdit = dataset?.canEdit === 'true'
    maxLength = Number.parseInt(dataset?.maxLength ?? '0') || Infinity
  })

  async function editDescription() {
    const tid = parseTid()
    const response: string | { message: string } = await fetch.get(
      `/texture/${tid}/description`,
      {
        raw: true,
      },
    )
    if (typeof response === 'string') {
      raw = response
      isEditing = true
    } else {
      notify.toast.error(response.message)
      return
    }
  }

  async function submitDescription() {
    isSubmitting = true
    const tid = parseTid()
    const response: string | { message: string } = await fetch.put(
      `/texture/${tid}/description`,
      {
        description: raw,
      },
    )
    isSubmitting = false
    if (typeof response === 'string') {
      description = response
      isEditing = false
    } else {
      notify.toast.error(response.message)
    }
  }
</script>

<style>
  description-content :global(h1),
  description-content :global(h2) {
    padding-bottom: 0.3rem;
    border-bottom: 1px solid #eaecef;
  }

  description-content :global(blockquote) {
    color: #aaa;
    border-left: 0.3rem solid #aaa;
  }

  description-content :global(hr) {
    border-top-width: 4px;
  }
</style>

<div class="card card-secondary">
  <div class="card-header">
    <div class="d-flex justify-content-between align-items-center">
      <h3 class="card-title">{t('texture-description.description')}</h3>
      {#if canEdit && !isEditing}
        <button
          class="btn btn-secondary btn-sm float-right"
          on:click={editDescription}>
          <i class="fas fa-edit" />
        </button>
      {/if}
    </div>
  </div>
  <div class="card-body">
    {#if isEditing}
      <textarea class="form-control" rows="10" bind:value={raw} />
    {:else if isEmptyDescription}
      <p>
        <i>{t('texture-description.empty')}</i>
      </p>
    {:else}
      <description-content>
        {@html description}
      </description-content>
    {/if}
  </div>
  {#if isEditing}
    <div class="card-footer">
      {#if isLengthExceeded}
        <div class="alert alert-info">
          {t('texture-description.exceeded', { max: maxLength })}
        </div>
      {/if}
      <div class="d-flex justify-content-between">
        <button
          class="btn btn-primary"
          disabled={isSubmitting || isLengthExceeded}
          on:click={submitDescription}>
          {#if isSubmitting}
            <span>
              <i class="fas fa-sync fa-spin" />
            </span>
          {:else}{t('general.submit')}{/if}
        </button>
        <button
          class="btn btn-secondary"
          disabled={isSubmitting}
          on:click={() => (isEditing = false)}>
          {t('general.cancel')}
        </button>
      </div>
    </div>
  {/if}
</div>

// plugins/texture-description/assets/Description.tsx
import React, { useState, useEffect } from 'react'
import ReactDOM from 'react-dom'
import { fetch, t, notify } from 'blessing-skin'
import './markdown.scss'

const el = document.querySelector<HTMLDivElement>('#texture-description')

function parseTid(): string {
  const { pathname } = location
  const matches = /(\d+)$/.exec(pathname)

  return matches?.[1] ?? '0'
}

const Description: React.FC = () => {
  const [description, setDescription] = useState('')
  const [raw, setRaw] = useState<string | null>(null)
  const [maxLength, setMaxLength] = useState(Infinity)
  const [canEdit, setCanEdit] = useState(false)
  const [isEditing, setIsEditing] = useState(false)
  const [isSubmitting, setIsSubmitting] = useState(false)

  useEffect(() => {
    const getDescription = async () => {
      const tid = parseTid()
      const description: string = await fetch.get(`/texture/${tid}/description`)
      setDescription(description)
    }
    getDescription()
  }, [])

  useEffect(() => {
    const dataset = el?.dataset
    setCanEdit(dataset?.canEdit === 'true')
    setMaxLength(Number.parseInt(dataset?.maxLength ?? '0') || Infinity)
  }, [])

  const handleEditContent = async (event: React.MouseEvent) => {
    event.preventDefault()
    if (raw === null) {
      const tid = parseTid()
      const response: string | { message: string } = await fetch.get(
        `/texture/${tid}/description`,
        {
          raw: true,
        },
      )
      if (typeof response === 'string') {
        setRaw(response)
      } else {
        notify.toast.error(response.message)
        return
      }
    }
    setIsEditing(true)
  }

  const handleTextareaChange = ({
    target: { value },
  }: React.ChangeEvent<HTMLTextAreaElement>) => {
    setRaw(value)
  }

  const handleSubmit = async () => {
    setIsSubmitting(true)
    const tid = parseTid()
    const response: string | { message: string } = await fetch.put(
      `/texture/${tid}/description`,
      {
        description: raw,
      },
    )
    setIsSubmitting(false)
    if (typeof response === 'string') {
      setDescription(response)
      setIsEditing(false)
    } else {
      notify.toast.error(response.message)
    }
  }

  const handleCancelEdit = () => setIsEditing(false)

  const isEmptyDescription = description.trim() === ''
  if (!canEdit && isEmptyDescription) {
    return null
  }

  const isLengthExceeded = (raw?.length ?? 0) > maxLength

  return (
    <div className="card card-secondary">
      <div className="card-header">
        <div className="d-flex justify-content-between">
          <h3 className="card-title">{t('texture-description.description')}</h3>
          {canEdit && !isEditing && (
            <a
              className="float-right btn-edit"
              href="#"
              onClick={handleEditContent}
            >
              <i className="fas fa-edit"></i>
            </a>
          )}
        </div>
      </div>
      <div className="card-body">
        {isEditing ? (
          <textarea
            className="form-control"
            rows={10}
            value={raw ?? ''}
            onChange={handleTextareaChange}
          ></textarea>
        ) : isEmptyDescription ? (
          <p>
            <i>{t('texture-description.empty')}</i>
          </p>
        ) : (
          <div dangerouslySetInnerHTML={{ __html: description }}></div>
        )}
      </div>
      {isEditing && (
        <div className="card-footer">
          {isLengthExceeded && (
            <div className="alert alert-info">
              {trans('texture-description.exceeded', { max: maxLength })}
            </div>
          )}
          <div className="d-flex justify-content-between">
            <button
              className="btn btn-primary"
              disabled={isSubmitting || isLengthExceeded}
              onClick={handleSubmit}
            >
              {isSubmitting ? (
                <span>
                  <i className="fas fa-sync fa-spin"></i>
                </span>
              ) : (
                t('general.submit')
              )}
            </button>
            <button
              className="btn btn-secondary"
              disabled={isSubmitting}
              onClick={handleCancelEdit}
            >
              {t('general.cancel')}
            </button>
          </div>
        </div>
      )}
    </div>
  )
}

ReactDOM.render(<Description />, el)
