// plugins/texture-description/assets/UploadEditor.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte'
  import { event, t } from 'blessing-skin'

  let description = ''
  let maxLength = Infinity

  onMount(() => {
    const off = event.on('beforeFetch', (request: { data: FormData }) => {
      request.data.set('description', description)
    })
    onDestroy(off)
  })

  onMount(() => {
    const input = document.querySelector<HTMLInputElement>('#description-limit')
    maxLength = Number.parseInt(input?.value ?? '0') || Infinity
  })
</script>

<label for="description-editor">{t('texture-description.description')}</label>
<textarea
  id="description-editor"
  class="form-control"
  rows="9"
  bind:value={description} />
{#if description.length > maxLength}
  <div className="alert alert-info mt-2">
    {t('texture-description.exceeded', { max: maxLength })}
  </div>
{/if}

// plugins/texture-description/assets/UploadEditor.tsx
import React, { useState, useEffect } from 'react'
import ReactDOM from 'react-dom'
import { event, t } from 'blessing-skin'

const UploadEditor: React.FC = () => {
  const [description, setDescription] = useState('')
  const [maxLength, setMaxLength] = useState(Infinity)

  useEffect(() => {
    return event.on('beforeFetch', (request: { data: FormData }) => {
      request.data.set('description', description)
    })
  }, [description])

  useEffect(() => {
    const input = document.querySelector<HTMLInputElement>('#description-limit')
    setMaxLength(Number.parseInt(input?.value ?? '0') || Infinity)
  }, [])

  const handleTextareaChange = ({
    target: { value },
  }: React.ChangeEvent<HTMLTextAreaElement>) => {
    setDescription(value)
  }

  return (
    <>
      <label>{t('texture-description.description')}</label>
      <textarea
        className="form-control"
        rows={9}
        onChange={handleTextareaChange}
      ></textarea>
      {description.length > maxLength && (
        <div className="alert alert-info mt-2">
          {trans('texture-description.exceeded', { max: maxLength })}
        </div>
      )}
    </>
  )
}

event.on('mounted', () => {
  const lastFormGroup = document.querySelector<HTMLDivElement>(
    '#file-input .form-group:nth-child(3)',
  )
  if (lastFormGroup) {
    const formGroup = document.createElement('div')
    formGroup.className = 'form-group'
    lastFormGroup.after(formGroup)
    ReactDOM.render(<UploadEditor />, formGroup)
  }
})
